import Head from "next/head";

import { useRouter } from "next/router";
type Props = {
  host: string;
  id: string;
  time: string;
};
export default function Post({ host, id, time }: Props) {
  const router = useRouter();

  // Host available on query from router if blocking or fallback
  const query = router.query;

  // Or params
  console.log(host, id, time, query);

  return (
    <div>
      <Head>
        <title>Next Multi Host Test posts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Posts: {host}</h1>
      <p>
        <b>Generated At haha:</b>
        <i>{time}</i>
      </p>
    </div>
  );
}

export async function getStaticProps(context: any) {
  // Available on server render
  console.log("getStaticProps", context);

  const host = context.params.host;

  const time = Date.now();

  return {
    props: {
      host,
      time,
    },
    // revalidate: 10,
  };
}

export async function getStaticPaths() {
  return {
    paths: [],
    fallback: "blocking",
  };
}
